---
# 1. Coloca o disco secundário online (Disco 1 vindo do vSphere)
- name: Garantir que o segundo disco esta online
  ansible.windows.win_powershell:
    script: |
      Get-Disk -Number 1 | Set-Disk -IsOffline $false
  ignore_errors: true # Evita travas caso o disco já estivesse online e pronto

# 2. Cria a partição usando a letra D:\ ocupando todo o espaço disponível
- name: Criar particao para o drive D:\
  community.windows.win_partition:
    drive_letter: D
    disk_number: 1
    partition_size: -1
    state: present

# 3. Formata a partição recém-criada como NTFS
- name: Formatar o drive D:\ como NTFS
  community.windows.win_format:
    drive_letter: D
    file_system: NTFS
    new_label: Programas
    state: present

# 4. Criar o diretório D:\Programas no disco secundário formatado
- name: Criar o diretorio D:\Programas
  ansible.windows.win_file:
    path: 'D:\Programas'
    state: directory

# 5. Instalar o Chocolatey (Gerenciador de pacotes padrão para Windows 11)
- name: Garantir que o Chocolatey esta instalado na maquina
  chocolatey.chocolatey.win_chocolatey:
    name: chocolatey
    state: present

# 6. Ajustar políticas básicas de segurança local para automação do Windows 11
- name: Configurar LocalAccountTokenFilterPolicy para permitir administradores locais via rede
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: LocalAccountTokenFilterPolicy
    data: 1
    type: dword
    state: present