vsphere_server        = "192.168.31.13"
datacenter            = "MVRC-DC"
cluster               = "Xeon"
datastore             = "VS1_SSD2TB"
datastore_programas   = "VS1_HD500GB"
network_vm            = "VM Network"
network_ad            = "VLAN_AD"
template_name         = "W11_25H2_ANSIBLE"
vm_name               = "Win11_AD"
vm_count              = 1
num_cpus              = 4
memory_mb             = 4096
disk_d_size_gb        = 80
static_ip_start       = 50
ad_gateway            = "172.16.0.254"
ad_dns_primary        = "172.16.0.254"
ad_prefix_length      = 24