#########################################################################
# DOMAIN
#########################################################################

company_domain: mvrc.local

#########################################################################
# AD NETWORK
#########################################################################

ad_prefix_length: 24
ad_gateway: 172.16.0.254
ad_dns_primary: 172.16.0.254

#########################################################################
# NTP
#########################################################################

ntp_server: a.st1.ntp.br