---
#########################################################################
# REDE AD
#########################################################################

ad_prefix_length: 24
ad_gateway: "172.16.0.254"
ad_dns_primary: "172.16.0.254"

#########################################################################
# DOMINIO
#########################################################################

company_domain: "mvrc.local"