---
- name: Configurar VM de aplicação
  hosts: app_servers
  become: true
  vars:
    app_user: "mvrc"
    app_dir: "/opt/app"
    static_ip: "192.168.31.49"
    gateway: "192.168.31.1"
    dns_primary: "192.168.31.1"
    dns_secondary: "8.8.8.8"

  pre_tasks:
    - name: Aguardar SSH ficar disponível
      wait_for_connection:
        delay: 10
        timeout: 120

    - name: Atualizar cache de pacotes
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - network
    - base
    - java
    - nodejs
    - nginx
    - app-user
    - docker