---
- name: Configurar VM Windows
  hosts: windows_vm
  gather_facts: true

  tasks:

    #####################################################################
    # BASE
    #####################################################################

    - name: Executar role BASE
      ansible.builtin.include_role:
        name: base
        apply:
          tags:
            - base
      tags:
        - base

    - name: Executar role NETWORK
      ansible.builtin.include_role:
        name: network
        apply:
          tags:
            - base
      tags:
        - base

    #####################################################################
    # DEV
    #####################################################################

    - name: Executar role PYTHON
      ansible.builtin.include_role:
        name: python
        apply:
          tags:
            - dev
      tags:
        - dev

    - name: Executar role JAVA
      ansible.builtin.include_role:
        name: java
        apply:
          tags:
            - dev
      tags:
        - dev

    - name: Executar role NODEJS
      ansible.builtin.include_role:
        name: nodejs
        apply:
          tags:
            - dev
      tags:
        - dev

    - name: Executar role DEVTOOLS
      ansible.builtin.include_role:
        name: devtools
        apply:
          tags:
            - dev
      tags:
        - dev

    #####################################################################
    # FINALIZE
    #####################################################################

    - name: Executar role FINALIZE
      ansible.builtin.include_role:
        name: finalize
        apply:
          tags:
            - finalize
      tags:
        - finalize